### ISSUE TITLE
Inconsistent storage location

### ISSUE THREAD

**Issue by Florke64** [Truemmerer/animated_wallpaper_helper#11]
Greetings!

Issue is that awp.sh uses variable `$Bilddir` and `$Download` as storage location.
However, later on - when saving `lastpicture.txt` and `lastvideo.txt` files - it ignores that variable and goes with `~/Animated_Wallpapers`.

I suggest moving these text files to the hidden `.cache` directory in user's homedir (`~/.cache/Animated_Wallpapers` ?).

My second suggestion would be to replace `$Bilddir` and `$Download` variables with only one called `$rootDir` and point it to `~/Videos/Animated_Wallpapers`. This is just example location, it could be still user's homedir instead of "Videos". (P.S. according to xdg-user-dirs, you are making a lot of noise in homedir )

This small change will make this script more complaint with common standards and, honestly, a lot more friendly.

**Comment by Florke64** [comment]
I've made a Pull Request #12 to address that issue. Please review it and merge if you think it is reasonable.

**Comment by Truemmerer** [comment]
Hey, thanks a lot for your suggestions for improvement. I have added your code to the master.
I was also planning to do the video and will implement it soon.

**Comment by Florke64** [comment]
Closing this issue as #12 and #14 were merged. Thank you.
