### ISSUE TITLE
Filenames with spaces in them

### ISSUE THREAD

**Issue by Florke64** [Truemmerer/animated_wallpaper_helper#13]
Hello,

Just been playing around with this script and found a bug in `awp/awp.sh`.
It looks like, spaces in filenames make it crash for many reasons.
One of the reasons is call to `gsettings`, another might be `animated-wallpaper`.
Part of the path is most probably interpreted as the next command arguments.

**Solution:**
I believe it would be enough to add a quote characters around the paths in script, where variables are involved.

**For example:**
Instead of this: `mkdir -p $Bilddir`
Something like this: `mkdir -p "$Bilddir"`

It should be amended everywhere in `awp.sh` in my opinion.

**Comment by Truemmerer** [comment]
I will take over this tomorrow. Thank you for the suggestion.

**Comment by Truemmerer** [comment]
Could you look over there, please? It should now be adjusted as you suggested.

**Comment by Florke64** [comment]
It looks fine, I am testing it right now.

**Comment by Florke64** [comment]
I believe it has been fixed in recent commits
