### ISSUE TITLE
Default storage folder

### ISSUE THREAD

**Issue by Truemmerer** [Truemmerer/animated_wallpaper_helper#15]
From @FlrQue  

My second suggestion would be to replace $Bilddir and $Download variables with only one called $rootDir and point it to ~/Videos/Animated_Wallpapers. This is just example location, it could be still user's homedir instead of "Videos". (P.S. according to xdg-user-dirs, you are making a lot of noise in homedir )

-----------------------------------

**Comment by Truemmerer** [comment]
According to the suggestion, I would put the folder in the user's Videos folder. 
```

Userdirs="$HOME/.config/user-dirs.dirs" 
if [ -f "$Userdirs" ]; then
       source "$HOME/.config/user-dirs.dirs"
else
    XDG_VIDEOS_DIR="$HOME/Videos"   
fi 

Download="$XDG_VIDEOS_DIR/Animated_Wallpapers"
Bilddir="$Download/Bild"
Cachedir="$HOME/.cache/Animated_Wallpapers"
Appdir="/usr/local/share/awp"
FILEABOUT="$Appdir/about.txt"
```
And to facilitate an easy changeover, add the following:

```
Olddir="$HOME/Animated_Wallpapers" 
if [ -d "$Olddir" ]; then 
    cp -r $Olddir/* "$Download"
    rm -rf "$Olddir"
    zenity --info \
    --text="The animated backgrounds have been moved to your Video folder: $Download"
fi

```

**Comment by Florke64** [comment]
This is great, it is better than what was on my mind.
Good decision to source `user-dirs.dirs` file.

**Comment by Truemmerer** [comment]
is merged
