### ISSUE TITLE
awp.sh starts as a root if is ran right after installation

### ISSUE THREAD

**Issue by Florke64** [Truemmerer/animated_wallpaper_helper#16]
![root-after-installation](https://user-images.githubusercontent.com/23085743/151031493-a3f87fba-6835-4054-b5bd-d4a8855275bc.png)

I will try to resolve this - posting just for the reference.

**Comment by Truemmerer** [comment]
@FlrQue Have you start the latest install.sh with root ?
I think I need to add a query to start the script as a normal user.

**Comment by Truemmerer** [comment]
Now it is fixed, I think :)

**Comment by Florke64** [comment]
Please see my commit too

**Comment by Truemmerer** [comment]
Thank you very much. Is merged :)
