### ISSUE TITLE
Floating `fi` at end of file

### ISSUE THREAD

**Issue by Da-Scher** [Truemmerer/animated_wallpaper_helper#20]
There seems to be a floating `fi` right at the end of the `install.sh` file. Removing the `fi` does not seem to stop the installer, but my arch desktop refused to run `awp.sh` after the installation because of insufficient permissions.

**Comment by lucaliceti** [comment]
I am having the exact issue. Don't know how to solve it because the file has permission to execute.

**Comment by Florke64** [comment]
> I am having the exact issue. Don't know how to solve it because the file has permission to execute.

@lucaliceti Floating `fi` should not generate any major error :thinking: 
Consider better explaining your experience under the separate issue.
