### ISSUE TITLE
Automatic Install doest Work On Ubuntu 22.00 LTS

### ISSUE THREAD

**Issue by Evangelio34** [Truemmerer/animated_wallpaper_helper#21]
![image](https://user-images.githubusercontent.com/90260698/164559466-031bac43-b1d0-4998-bfcf-cc2a8bda236a.png)
![image](https://user-images.githubusercontent.com/90260698/164559528-02dda6ba-7da8-4c5e-8bec-7b9b65817fef.png)

**Comment by Truemmerer** [comment]
I download now Ubuntu 22.04 and test it :)

**Comment by Florke64** [comment]
Hi, @Inosuke-jijijija 

Did you try running it with `bash ./install.sh` ?
Or just giving it execute permission (`sudo chmod +x install.sh`) and running it with regular `./install.sh` ?

Are you facing the same issue then?

**Comment by Truemmerer** [comment]
The problem occurs when you call the installation script with sh ./install.sh on Ubuntu.
I have changed the readme to bash ./install.sh.

**Comment by pablodz** [comment]
Tested in ubuntu 22.04 LTS without problems of install script
