### ISSUE TITLE
Wallpaper disappear at every restart

### ISSUE THREAD

**Issue by shiipou** [Truemmerer/animated_wallpaper_helper#23]
On PopOS, the wallpaper turn black everytime I restart the computer.

I install it using a youtube video and that work well.
the video got downloaded at `~/Videos/Animated_Wallpapers/rising_light_animated.mkv` and got converted to webm at `~/Videos/Animated_Wallpapers/rising_light_animated-convert.webm` 

So at next restart I have to re-run the script and re-create the wallpaper using a local path (To not re-download all the video)

If you need any other info, just tell me.

**Comment by Truemmerer** [comment]
Hey @shiipou

I just tried it out. 
Apparently PopOS! is missing the autostart folder. As a result, the script is not placed there. 

$HOME/.config/autostart/

I add in the script a `mkdir -p $HOME/.config/autostart/` then the problem should be solved.

**Comment by Truemmerer** [comment]
.

**Comment by shiipou** [comment]
Oh thank guy, I'll try it this evening (UTC+2)
Thanks for sharing.

**Comment by Truemmerer** [comment]
Did it work for you @shiipou ?

**Comment by shiipou** [comment]
> Did it work for you @shiipou ?

Yes that work, sorry I replied before.
